"""Rebuild the two damaged/missing JSON sidecars in analysis_out/findings/.

- P003_US_train_s3_shape.json was truncated mid-write (it ended on a
  '<!--JSON-CHUNK-3-->' marker) and would not parse. Rebuilt from its intact .md.
- P005_US_test_s2_shape.json was never written. Rebuilt from its intact .md.

Every numeric field is COMPUTED from analysis_out/profile/*.json here, not
transcribed, so the sidecars cannot drift from the profile. Prose fields mirror
the .md deliverables. Read-only on profile/; writes only the two sidecars.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
PROF = os.path.join(ROOT, "analysis_out", "profile")
FIND = os.path.join(ROOT, "analysis_out", "findings")


def load(name):
    with open(os.path.join(PROF, name), encoding="utf-8") as fh:
        return json.load(fh)


def pct(a, b, nd=4):
    return round(100.0 * a / b, nd) if b else None


def comma_identity(s):
    """rows - addr_empty vs has_comma: the comma invariant, per country slice."""
    ne = s["rows"] - s["addr_empty"]
    return {"rows": s["rows"], "addr_empty": s["addr_empty"],
            "rows_minus_addr_empty": ne, "has_comma": s["has_comma"],
            "comma_less_nonempty_rows": ne - s["has_comma"],
            "has_comma_pct_of_rows": pct(s["has_comma"], s["rows"])}


def hist(s, nd=3):
    """len_hist -> ordered [{bucket,count,pct,cum_pct}] sorted by bucket floor."""
    out = []
    for k in sorted(s["len_hist"], key=int):
        c = s["len_hist"][k]
        out.append({"bucket": f"{int(k)}-{int(k) + 9}", "count": c,
                    "pct_of_country_rows": pct(c, s["rows"], nd)})
    tot = sum(b["count"] for b in out)
    run = 0
    for b in out:
        run += b["count"]
        b["cum_pct"] = pct(run, tot, nd)
    return out


def tail_count(h, floor):
    """Sum counts of buckets whose floor is >= floor."""
    return sum(b["count"] for b in h if int(b["bucket"].split("-")[0]) >= floor)


def cum_at(h, bucket_start):
    return next(b["cum_pct"] for b in h if b["bucket"].startswith(bucket_start))


def pooled_comma():
    """Comma-less row totals per country across ALL six profile files."""
    agg = {}
    for name in sorted(os.listdir(PROF)):
        if not name.endswith(".json"):
            continue
        d = load(name)
        for c, s in d["by_country"].items():
            a = agg.setdefault(c, {"rows": 0, "comma_less": 0, "profile_files": 0})
            a["rows"] += s["rows"]
            a["comma_less"] += s["rows"] - s["addr_empty"] - s["has_comma"]
            a["profile_files"] += 1
    for a in agg.values():
        a["comma_less_pct"] = round(100.0 * a["comma_less"] / a["rows"], 6)
    return agg



# ----------------------------------------------------------------- P003
t3 = load("train_s3.json")
us = t3["by_country"]["US"]
in_ = t3["by_country"]["India"]
ush = hist(us)
us_ge50 = tail_count(ush, 50)
us_le40 = tail_count(ush, 0) - us_ge50

p003 = {
    "task_id": "P003",
    "family": "A-profile",
    "title": "[US] train_s3: shape, null rates, length distribution",
    "source_profile": "analysis_out/profile/train_s3.json",
    "deliverable": "analysis_out/findings/P003_US_train_s3_shape.md",
    "sidecar_rebuilt": True,
    "sidecar_rebuild_note": (
        "The original sidecar was truncated mid-write and would not parse as JSON. "
        "It was regenerated by rebuilding_sidecars.py, which recomputes every "
        "numeric field from the profile. The .md deliverable was intact and was "
        "not modified."),
    "dataset_touched": False,
    "network_used": False,
    "upstream_modified": False,
    "headline": (
        f"US slice of train_source3 is {us['rows']:,} rows "
        f"({pct(us['rows'], t3['rows'])}% of the {t3['rows']:,}-row file) and is "
        f"structurally clean: name_empty=0, prefix_bad=0. Two findings: (1) "
        f"has_comma ({us['has_comma']:,}) equals rows-addr_empty EXACTLY, so 100% "
        f"of non-empty US addresses contain a comma; (2) normalize.py:337 gates pin "
        f"on country=='India' but US dig6/row={us['dig6'] / us['rows']:.5f} vs India "
        f"{in_['dig6'] / in_['rows']:.6f}, so the gate admits only {in_['dig6']:,} "
        f"India rows while excluding {us['dig6']:,} US rows."),
    "most_important_number": {
        "value": round((us["dig6"] / us["rows"]) / (in_["dig6"] / in_["rows"]), 1),
        "unit": "x",
        "meaning": (
            f"US/India per-row dig6 ratio. The country the pin gate ADMITS has "
            f"{round((us['dig6'] / us['rows']) / (in_['dig6'] / in_['rows']), 1)}x "
            f"FEWER six-digit runs per row than the country it EXCLUDES, inverting "
            f"the gate's apparent intent: {us['dig6']:,} US rows carry a 6-digit "
            f"run versus {in_['dig6']:,} Indian rows."),
        "arithmetic": (
            f"({us['dig6']} / {us['rows']}) / ({in_['dig6']} / {in_['rows']}) = "
            f"{(us['dig6'] / us['rows']) / (in_['dig6'] / in_['rows']):.1f}"),
    },
    "shape": {
        "file_rows": t3["rows"],
        "file_rows_field": "rows",
        "us_rows": us["rows"],
        "india_rows": in_["rows"],
        "country_sum_check": (
            f"{us['rows']} + {in_['rows']} = {us['rows'] + in_['rows']} (equals rows; "
            "no hidden third country)"),
        "us_share_pct": pct(us["rows"], t3["rows"]),
        "us_share_arithmetic": f"{us['rows']} / {t3['rows']} = {us['rows'] / t3['rows']:.6f}",
        "india_share_pct": pct(in_["rows"], t3["rows"]),
        "countries_present": sorted(t3["by_country"]),
        "france_present": "France" in t3["by_country"],
        "cols": t3["cols"],
        "us_to_india_row_ratio": round(us["rows"] / in_["rows"], 3),
    },
    "null_rates_us": {
        "rows": us["rows"],
        "name_empty": us["name_empty"],
        "name_empty_pct": pct(us["name_empty"], us["rows"]),
        "addr_empty": us["addr_empty"],
        "addr_empty_pct": pct(us["addr_empty"], us["rows"]),
        "prefix_bad": us["prefix_bad"],
        "prefix_bad_pct": pct(us["prefix_bad"], us["rows"]),
        "assessment": (
            "CLEAN. Zero name nulls, zero entity_id prefix violations. The "
            "address-null rate is already absorbed by prep.py:23 fill_null(\"\") so "
            "it degrades to an empty token list rather than raising."),
    },
    "null_rates_india": {
        "rows": in_["rows"],
        "name_empty": in_["name_empty"],
        "addr_empty": in_["addr_empty"],
        "addr_empty_pct": pct(in_["addr_empty"], in_["rows"]),
        "prefix_bad": in_["prefix_bad"],
    },
    "lengths": {
        "us": {
            "name_chars": us["name_chars"],
            "mean_name_chars": round(us["name_chars"] / us["rows"], 3),
            "mean_name_arithmetic": f"{us['name_chars']} / {us['rows']} = {us['name_chars'] / us['rows']:.3f}",
            "addr_chars": us["addr_chars"],
            "mean_addr_chars_all_rows": round(us["addr_chars"] / us["rows"], 3),
            "mean_addr_chars_nonempty": round(us["addr_chars"] / (us["rows"] - us["addr_empty"]), 3),
            "name_tokens": us["name_tokens"],
            "name_tokens_per_name": round(us["name_tokens"] / us["rows"], 3),
            "num_digits": us["num_digits"],
            "num_digits_per_row": round(us["num_digits"] / us["rows"], 3),
            "has_digit_name": us["has_digit_name"],
            "has_digit_name_pct": pct(us["has_digit_name"], us["rows"]),
            "alpha_only_addr": us["alpha_only_addr"],
            "alpha_only_addr_pct": pct(us["alpha_only_addr"], us["rows"]),
        },
        "india": {
            "mean_name_chars": round(in_["name_chars"] / in_["rows"], 3),
            "mean_addr_chars_all_rows": round(in_["addr_chars"] / in_["rows"], 3),
            "mean_addr_chars_nonempty": round(in_["addr_chars"] / (in_["rows"] - in_["addr_empty"]), 3),
            "name_tokens_per_name": round(in_["name_tokens"] / in_["rows"], 3),
            "num_digits_per_row": round(in_["num_digits"] / in_["rows"], 3),
            "has_digit_name_pct": pct(in_["has_digit_name"], in_["rows"]),
            "alpha_only_addr_pct": pct(in_["alpha_only_addr"], in_["rows"]),
        },
        "note": (
            "Two mean-address figures are given because addr_chars counts empty "
            "strings as 0 characters (build_profile.py:102-103); both denominators "
            "are stated so neither is ambiguous."),
    },
    "name_length_histogram_us": {
        "field": "by_country.US.len_hist",
        "buckets": ush,
        "bucket_sum": sum(b["count"] for b in ush),
        "bucket_sum_equals_rows": sum(b["count"] for b in ush) == us["rows"],
        "modal_bucket": max(ush, key=lambda b: b["count"])["bucket"],
        "ge_50_count": us_ge50,
        "ge_50_pct": pct(us_ge50, us["rows"]),
        "le_49_pct": pct(us_le40, us["rows"]),
        "us_top_bucket": ush[-1]["bucket"],
        "india_top_bucket": sorted(in_["len_hist"], key=int)[-1],
        "shape": (
            "unimodal, right-skewed, hard ceiling. The US top bucket is 80-89 while "
            "India's extends to 120, so US names are markedly shorter, consistent "
            "with India's compounding multi-word transliterations."),
    },
    "comma_identity": {
        "claim": (
            "In the US slice has_comma == rows - addr_empty EXACTLY, implying 100% "
            "of non-empty US addresses contain at least one comma."),
        "us": comma_identity(us),
        "india": comma_identity(in_),
        "implication": (
            "normalize.py:322 splits on ',' and normalize.py:328-335 matches whole "
            "components against STATE_MAPS. The uniform US comma structure is the "
            "precondition for that exact-match state path to work."),
        "india_off_by_one": (
            "Exactly 1 Indian row has content but no comma. Noted as a curiosity, "
            "not a defect."),
    },
    "digit_runs_and_pin_gate": {
        "code": (
            "normalize.py:336-338 captures pin only when len(n)==6 and "
            "country=='India'"),
        "us": {"dig5": us["dig5"], "dig5_per_row": round(us["dig5"] / us["rows"], 5),
               "dig6": us["dig6"], "dig6_per_row": round(us["dig6"] / us["rows"], 5)},
        "india": {"dig5": in_["dig5"], "dig5_per_row": round(in_["dig5"] / in_["rows"], 5),
                  "dig6": in_["dig6"], "dig6_per_row": round(in_["dig6"] / in_["rows"], 6)},
        "rows_eligible_under_gate": in_["dig6"],
        "rows_excluded_by_gate_us": us["dig6"],
        "per_row_ratio_x": round((us["dig6"] / us["rows"]) / (in_["dig6"] / in_["rows"]), 1),
        "interpretation": (
            f"run_blocking.py:9 and keys.py:44,58 promote pin into a first-class "
            f"blocking key, so that key is effectively inert for India "
            f"({in_['dig6']} rows = {pct(in_['dig6'], in_['rows'])}% of India) and "
            f"entirely absent for the US in this slice, despite US dig5 "
            f"({us['dig5']:,} = {pct(us['dig5'], us['rows'])}%/row) indicating US "
            f"rows are rich in digit runs."),
        "caveat": (
            "dig5/dig6 count OCCURRENCES (build_profile.py:115-116), not distinct "
            "rows, so every per-row figure here is an UPPER BOUND on the distinct-row "
            "rate. The conclusion holds either way because the bound is what is used."),
    },
    "statistical_power": {
        "n": us["rows"],
        "method": "1.96*sqrt(p(1-p)/n) binomial half-width at 95%",
        "half_width_pp_at_p_0_5": round(1.96 * (0.25 / us["rows"]) ** 0.5 * 100, 4),
        "verdict": (
            "Yes, comfortably large enough to conclude from. Differences of more "
            "than a tenth of a percentage point are real."),
        "scope_caveat": (
            "This slice cannot speak to France: train_source3 contains only US and "
            "India. Any France claim needs the test_s1/2/3 profiles."),
    },
    "already_checked_disposition": {
        "REFUTED-1_french_postal_codes": (
            "Not re-derived. This train slice contains no France rows at all, so the "
            "claim is untestable here and is neither supported nor contradicted."),
        "REFUTED-2_fr_regions_too_thin": (
            "Not re-derived. No France rows, so untestable here."),
    },
    "gaps": [
        "No per-row flag for 'contains a 5/6-digit number'; dig5/dig6 are occurrence "
        "counts, so exact row-level rates are unavailable and all per-row figures are "
        "upper bounds.",
        "No state/city/region field: normalize_address outputs are never captured by "
        "the profiler.",
        "No true-empty vs whitespace-only distinction: build_profile.py strips before "
        "testing emptiness, so '   ' is already counted as empty.",
        "Token counters are top-4000 and pruned of hapax (build_profile.py:45), so no "
        "vocabulary size, type-token ratio or unique-business count is derivable.",
    ],
    "recommendations": [
        "HIGH: revisit the pin gate at normalize.py:336-338. Confining pin to India "
        f"caps the pin blocking-key population at {in_['dig6']:,} rows while excluding "
        f"{us['dig6']:,} US rows in this slice. Whether extending it improves recall "
        "depends on false-positive volume, which this profile cannot measure.",
        "NO CHANGE: address nulls are already handled by prep.py:23 fill_null(\"\"); a "
        f"{pct(us['addr_empty'], us['rows'])}% address-null rate is a recall ceiling, "
        "not a crash risk.",
        "NO CHANGE (advisory): do not truncate ncore early. 99.044% of US names are "
        "<=49 chars and 74.5% sit in a single 10-wide bucket, so any character "
        "budget for blocking keys would need to sit above ~50 chars. No measurement "
        "of the current budget exists, so this is a caution, not a finding.",
    ],
    "deliverable_format_note": (
        "The two files were the only permitted outputs; this sidecar is the "
        "structured half of the P003 work order."),
}


# ----------------------------------------------------------------- P005
t2 = load("test_s2.json")
us2 = t2["by_country"]["US"]
fr2 = t2["by_country"]["France"]
in2 = t2["by_country"]["India"]
us2h = hist(us2)
pooled = pooled_comma()
fr2_less = fr2["rows"] - fr2["addr_empty"] - fr2["has_comma"]
fr2_ceiling = 100 - 100 * fr2_less / fr2["rows"]
us2_ge50 = tail_count(us2h, 50)

p005 = {
    "task_id": "P005",
    "family": "A-profile",
    "title": "[US] test_s2: shape, null rates, length distribution",
    "source_profile": "analysis_out/profile/test_s2.json",
    "deliverable": "analysis_out/findings/P005_US_test_s2_shape.md",
    "sidecar_rebuilt": True,
    "sidecar_rebuild_note": (
        "The sidecar was never written before the session ended. It was generated by "
        "rebuilding_sidecars.py from the profile, so every figure is computed rather "
        "than transcribed. The .md deliverable was intact and was not modified."),
    "dataset_touched": False,
    "network_used": False,
    "upstream_modified": False,
    "headline": (
        f"The US slice of test_source2 is {us2['rows']:,} rows, "
        f"{pct(us2['rows'], t2['rows'])}% of the {t2['rows']:,}-row file, and is "
        f"clean on every integrity axis: zero empty names, zero malformed entity_id "
        f"prefixes, and a name-length histogram summing exactly to the row count. "
        f"The important result is not a US defect: the US-wide comma invariant that "
        f"siblings P002/P003 reported is exact but NOT universal, and it breaks on "
        f"France in the very file this work order covers. Across all six profiles "
        f"has_comma == rows - addr_empty holds for {pooled['US']['rows']:,} of "
        f"{pooled['US']['rows']:,} US rows (zero exceptions), but for France it fails "
        f"on {fr2_less} rows in test_s2. normalize.py requires a WHOLE component to "
        f"equal a region key before it will emit a state, so France's state "
        f"resolution in test_s2 is bounded above at {fr2_ceiling:.4f}%, not 100.00%."),
    "most_important_number": {
        "value": fr2_less,
        "unit": "rows",
        "meaning": (
            f"Comma-less non-empty France rows in test_source2. Each parses to a "
            f"SINGLE component, which normalize.py:333 cannot match against "
            f"FR_REGIONS, so each is an upper bound on one lost state signal. This is "
            f"France-specific and entirely absent from the US slice in the same file."),
        "arithmetic": (
            f"{fr2['rows']} - {fr2['addr_empty']} - {fr2['has_comma']} = {fr2_less}"),
    },
    "shape": {
        "file_rows": t2["rows"],
        "file_rows_field": "rows",
        "us_rows": us2["rows"],
        "india_rows": in2["rows"],
        "france_rows": fr2["rows"],
        "country_sum_check": (
            f"{us2['rows']} + {in2['rows']} + {fr2['rows']} = "
            f"{us2['rows'] + in2['rows'] + fr2['rows']} (equals rows; no hidden country)"),
        "us_share_pct": pct(us2["rows"], t2["rows"]),
        "us_share_arithmetic": f"{us2['rows']} / {t2['rows']} = {us2['rows'] / t2['rows']:.6f}",
        "india_share_pct": pct(in2["rows"], t2["rows"]),
        "france_share_pct": pct(fr2["rows"], t2["rows"]),
        "countries_present": sorted(t2["by_country"]),
        "cols": t2["cols"],
    },
    "null_rates_us": {
        "rows": us2["rows"],
        "name_empty": us2["name_empty"],
        "name_empty_pct": pct(us2["name_empty"], us2["rows"]),
        "addr_empty": us2["addr_empty"],
        "addr_empty_pct": pct(us2["addr_empty"], us2["rows"]),
        "addr_empty_arithmetic": (
            f"{us2['addr_empty']} / {us2['rows']} = {us2['addr_empty'] / us2['rows']:.6f}"),
        "prefix_bad": us2["prefix_bad"],
        "prefix_bad_pct": pct(us2["prefix_bad"], us2["rows"]),
        "has_comma": us2["has_comma"],
        "has_comma_pct": pct(us2["has_comma"], us2["rows"]),
        "has_digit_name": us2["has_digit_name"],
        "has_digit_name_pct": pct(us2["has_digit_name"], us2["rows"]),
        "alpha_only_addr": us2["alpha_only_addr"],
        "alpha_only_addr_pct": pct(us2["alpha_only_addr"], us2["rows"]),
        "dig5_occurrences": us2["dig5"],
        "dig5_per_row": round(us2["dig5"] / us2["rows"], 5),
        "dig6_occurrences": us2["dig6"],
        "dig6_per_row": round(us2["dig6"] / us2["rows"], 5),
        "prefix_assessment": (
            "prefix_bad=0 is a non-vacuous check: build_profile.py:94 evaluates "
            "eid.startswith('S2-') per row, so 0 of 1,871,330 means the S2- prefix is "
            "a valid partition key for 100% of US rows in this file. No prefix repair "
            "is needed."),
    },
    "lengths_us": {
        "name_chars": us2["name_chars"],
        "mean_name_chars": round(us2["name_chars"] / us2["rows"], 4),
        "mean_name_arithmetic": (
            f"{us2['name_chars']} / {us2['rows']} = {us2['name_chars'] / us2['rows']:.4f}"),
        "addr_chars": us2["addr_chars"],
        "mean_addr_chars_all_rows": round(us2["addr_chars"] / us2["rows"], 4),
        "mean_addr_chars_nonempty": round(us2["addr_chars"] / (us2["rows"] - us2["addr_empty"]), 4),
        "name_tokens": us2["name_tokens"],
        "name_tokens_per_name": round(us2["name_tokens"] / us2["rows"], 4),
        "num_digits": us2["num_digits"],
        "num_digits_per_row": round(us2["num_digits"] / us2["rows"], 4),
        "note": (
            "The two mean-address figures differ by exactly the null rate because "
            "build_profile.py:102-103 adds len() of the STRIPPED string and len('') "
            "is 0. num_digits counts digits in the ADDRESS only "
            "(build_profile.py:114); has_digit_name is the separate name signal."),
    },
    "name_length_histogram_us": {
        "field": "by_country.US.len_hist",
        "buckets": us2h,
        "bucket_sum": sum(b["count"] for b in us2h),
        "bucket_sum_equals_rows": sum(b["count"] for b in us2h) == us2["rows"],
        "le_19_pct": cum_at(us2h, "10"),
        "le_39_pct": cum_at(us2h, "30"),
        "ge_50_count": us2_ge50,
        "ge_50_pct": pct(us2_ge50, us2["rows"]),
        "note": (
            "Because name_empty=0, all rows in the 0-9 bucket hold names of length "
            "1-9, not empty strings."),
    },
    "statistical_power": {
        "n": us2["rows"],
        "method": "1.96*sqrt(p(1-p)/n) binomial half-width at 95%",
        "verdict": "Yes. Every rate discussed is known to four decimal places.",
        "caveat": (
            f"The smallest effect discussed here ({fr2_less} rows = "
            f"{pct(fr2_less, fr2['rows'])}pp) is ~19x smaller than the sampling error "
            "on addr_empty. It is therefore detectable ONLY as an exact integer "
            "discrepancy against a structural identity, never as a rate difference."),
    },
    "new_finding_comma_invariant": {
        "identity": (
            "has_comma == rows - addr_empty, i.e. every non-empty address contains a "
            "comma."),
        "holds_for_us": True,
        "pooled_all_six_profiles": pooled,
        "pooled_verdict": (
            f"US 0 of {pooled['US']['rows']:,} comma-less rows (exact in all six "
            f"files); France {pooled['France']['comma_less']} of "
            f"{pooled['France']['rows']:,} ({pooled['France']['comma_less_pct']}%); "
            f"India {pooled['India']['comma_less']} of {pooled['India']['rows']:,} "
            f"({pooled['India']['comma_less_pct']}%)."),
        "france_test_s2": {
            "rows": fr2["rows"],
            "addr_empty": fr2["addr_empty"],
            "non_empty": fr2["rows"] - fr2["addr_empty"],
            "has_comma": fr2["has_comma"],
            "comma_less": fr2_less,
            "comma_less_pct_of_rows": pct(fr2_less, fr2["rows"]),
        },
        "mechanism": {
            "code": "_upstream/src/normalize.py:322-352",
            "how_verified": (
                "imported read-only and executed on SYNTHETIC strings only; the raw "
                "dataset was never opened"),
            "steps": [
                "line 322: comps = [c.strip() for c in s.split(',')]",
                "line 333: if ck in smap  -- requires a WHOLE component to equal a region key",
                "a single-component address therefore can never satisfy the state match",
            ],
        },
        "consequence": (
            f"France state resolution in test_s2 is bounded above at "
            f"{fr2_ceiling:.4f}%, not 100.00%."),
        "correction_to_record": (
            "The '100.00% (259,452/259,452, zero unmatched)' figure in the "
            "already_checked block is correct but was measured on test_s1 ONLY, which "
            "happens to contain exactly zero comma-less France rows. It must not be "
            "generalised to test_s2/test_s3, where the same code path fails on 180 "
            "and 153 rows respectively."),
    },
    "already_checked_disposition": {
        "REFUTED-1_french_postal_codes": (
            f"Not re-derived, and my evidence does NOT support it. US dig5/row here is "
            f"{us2['dig5'] / us2['rows']:.5f}, consistent with the 0.110 figure in the "
            f"record. France in this file has dig5={fr2['dig5']:,} over {fr2['rows']:,} "
            f"rows = {fr2['dig5'] / fr2['rows']:.5f}/row, matching the 0.005 quoted for "
            "test_s2. The pin guard is a real code defect whose impact is on US "
            "source-1 / India, not France."),
        "REFUTED-2_fr_regions_too_thin": (
            f"Largely agreed: FR_REGIONS has 14 entries covering 4 canonical values and "
            f"state resolution is near-total. But with a loud qualification -- the "
            f"100.00% figure is test_s1-only; in test_s2 the provable upper bound is "
            f"{fr2_ceiling:.4f}% ({fr2_less} rows) and in test_s3 it is 153 rows. This "
            f"does NOT rehabilitate the finding (0.026% is immaterial next to a "
            f"14-vs-52 dictionary gap) but it corrects a number that had been carried "
            f"into the record as file-independent."),
    },
    "gaps": [
        "No n_comps / component-count / component-position field. This is the single "
        "largest blind spot in the profile and it is what blocks the component-order "
        "question. build_profile.py:126 splits on [,;] only to feed the token counter "
        "and DISCARDS the component count.",
        "No pin field and no row-level has_5digit/has_6digit boolean. dig5/dig6 are "
        "occurrence counts, so they are upper bounds on distinct-row rates and are "
        "never reported here as row rates.",
        "No state/city/region field: normalize_address outputs are never captured, so "
        "the state figure is a BOUND derived from upstream code plus the comma "
        "identity, not a direct measurement of state resolution.",
        "No true-empty vs whitespace-only distinction: the builder strips before "
        "testing emptiness, so '   ' is already counted as empty.",
        f"Cannot determine whether the {fr2_less} comma-less France rows contain a house "
        "number (which would also kill city_comps) or a region name (which would still "
        f"resolve). The {fr2_less} figure is therefore strictly an UPPER BOUND on state loss.",
        "Token counters are top-4000 and pruned of hapax, so no vocabulary size, "
        "type-token ratio or unique-business count is derivable.",
        "Whether alpha_only_addr includes empty addresses is resolved by reading the "
        "builder (build_profile.py:117 is 'if ba and not any(...)', so empty "
        "addresses are EXCLUDED) rather than inferred.",
    ],
    "recommendations": [
        "HIGH (NEW): add an n_comps field to build_profile.py recording "
        "len([c for c in ba.split(',') if c.strip()]) per row. One field converts the "
        f"<={fr2_less} bound into a measured count and is the only way to settle the "
        "component-order question that two prior rounds flagged and could not reach. "
        "Expected effect: pure diagnostic, no pipeline change, one extra streaming "
        "counter at negligible cost.",
        "MEDIUM: make normalize_address tolerate single-component addresses. A fallback "
        "running region matching on the last (or first) comma-component's trailing "
        "tokens would recover state for those rows. The failure mechanism is CONFIRMED "
        "(demonstrated on real code); the fix and its recall/precision tradeoff are "
        "SPECULATIVE, because the profile cannot describe the 180 strings. Expected "
        f"effect: <={fr2_less} France rows in test_s2 and <=153 in test_s3 regain a "
        "region signal. Do NOT expect a leaderboard move at 0.026%.",
        "NO CHANGE: no null handling, prefix repair or name handling for US test_s2. "
        "name_empty and prefix_bad are exact zeros, and the 2.9448% address-null rate "
        "is already absorbed by prep.py:23 fill_null(\"\"). Manufacturing a fix here "
        "would be noise.",
        "NO CHANGE: no dictionary entry is warranted from this slice. This work order is "
        "a shape/null-rate profile and produced evidence of a PARSER robustness gap, "
        "not a missing token. I propose no CONFIRMED/LIKELY/SPECULATIVE dictionary "
        "entries.",
        "LOW (informational): record the comma invariant as a corpus-level fact WITH "
        "its exception count, so future agents do not generalise it from US to France. "
        f"The honest statement is: exact for {pooled['US']['rows']:,} US rows; violated "
        f"by {pooled['France']['comma_less']} France rows "
        f"({pooled['France']['comma_less_pct']}%) and {pooled['India']['comma_less']} "
        f"India rows.",
    ],
    "confidence_markers": {
        "CONFIRMED": [
            f"US test_s2 = {us2['rows']:,} rows, {pct(us2['rows'], t2['rows'])}% of file",
            "len_hist sums exactly to rows (integer identity)",
            "country_rows sums exactly to rows (integer identity)",
            "name_empty=0, prefix_bad=0 (exact zeros, build_profile.py:94,98)",
            f"US comma invariant exact in all six files (0 exceptions in {pooled['US']['rows']:,} rows)",
            f"France test_s2 has {fr2_less} comma-less non-empty rows (exact integer)",
            "a comma-less component yields state='' (executed real normalize.py on synthetic strings)",
        ],
        "CONFIRMED_as_bound": [
            f"France state resolution <= {fr2_ceiling:.4f}% in test_s2; the "
            "attainability of the bound is untested",
        ],
        "LIKELY": [
            "those 180 rows also lose city_comps (true iff they contain a house number; "
            "profile cannot tell)",
        ],
        "SPECULATIVE": [
            "the invariant reflects a fixed generator template (pattern-based inference, no generator data)",
            "a last-component region fallback would help (fix not measured)",
            "component order is inconsistent in French rows (ABANDONED: no n_comps/position field exists)",
        ],
    },
}

for name, obj in (("P003_US_train_s3_shape.json", p003),
                  ("P005_US_test_s2_shape.json", p005)):
    path = os.path.join(FIND, name)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(obj, fh, indent=1, ensure_ascii=False)
    print(f"wrote {name} ({os.path.getsize(path):,} bytes)")

print("pooled comma-less non-empty rows per country (all six profiles):")
for c, a in pooled.items():
    print(f"  {c:7s} {a['comma_less']:>5} of {a['rows']:>12,} ({a['comma_less_pct']}%)")
print(f"France test_s2 state-resolution ceiling: {fr2_ceiling:.4f}%")
