"""Write analysis_out/roster_state_manifest.json.

Generated rather than hand-edited so the counts in it are measured from the
roster at write time, not copied forward and left to rot.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "analysis_out", "roster_state_manifest.json")
TASKS = os.path.join(ROOT, "analysis_out", "tasks")
FIND = os.path.join(ROOT, "analysis_out", "findings")

tasks = []
for fn in sorted(os.listdir(TASKS)):
    if fn.endswith(".json"):
        with open(os.path.join(TASKS, fn), encoding="utf-8") as f:
            tasks.append(json.load(f))

fam: dict[str, int] = {}
for t in tasks:
    fam[t["family"]] = fam.get(t["family"], 0) + 1
done = [t for t in tasks
        if os.path.exists(os.path.join(ROOT, t["deliverable"]))]

orphans = os.path.join(FIND, "deprecated_slots")
n_orphans = len([f for f in os.listdir(orphans) if f.endswith(".md")]) \
    if os.path.isdir(orphans) else 0

manifest = {
    "_README": [
        "State manifest rewritten after the roster-integrity bugs were FIXED, "
        "not just measured.",
        "Re-checkable at any time: reconcile_roster.py (integrity), "
        "reconcile_progress.py (completeness).",
        "Generated by write_manifest.py, so the counts below are measured at "
        "write time rather than copied forward.",
    ],
    "roster_state": {
        "task_files_on_disk": len(tasks),
        "unique_ids": len({t["id"] for t in tasks}),
        "by_family": fam,
        "status": "HEALTHY - reconcile_roster.py CHECK 1, 2 and 3 all PASS",
        "family_A": "STABLE - A loops are deterministic over COUNTRIES x SOURCES.",
        "note": "The roster is 127 tasks, not 120. See BUG_5_silent_120_cap.",
    },
    "fixed_this_session": {
        "BUG_1_3_id_stability": {
            "status": "FIXED",
            "was": "id_for() existed but emit() never called it, so every task "
                   "got a bare sequential id. Any regeneration renumbered the B "
                   "family and detached 10 finished reports from their work "
                   "orders.",
            "fix": "emit() now takes a (family, kind, dictionary, country) "
                   "slot; resolve_id() returns the ledger-pinned id when the "
                   "slot is known, and next_d_id() skips ids already reserved by "
                   "a completed deliverable, so a fresh task can never overwrite "
                   "a finished one. emit() raises on any duplicate id, and a "
                   "post-write self-check fails the build if a filename "
                   "disagrees with its id.",
            "evidence": "reconcile_roster.py: CHECK 1 PASS (filename == id), "
                        "CHECK 2 PASS (no collisions), CHECK 3 PASS (every "
                        "completed deliverable maps to a live task).",
        },
        "BUG_4_stale_generation_files": {
            "status": "FIXED",
            "was": "build() wrote the new roster without removing the previous "
                   "generation, so analysis_out/tasks/ held two rosters at once "
                   "- the direct cause of 135 files with 133 unique ids.",
            "fix": "build() deletes any *.json in OUTDIR not in the new "
                   "keep-set before writing.",
        },

        "BUG_5_silent_120_cap": {
            "status": "FIXED",
            "was": "tasks = TASKS[:120] silently discarded 7 tasks with no "
                   "warning. The 7 were D121-D123 (gaps in LEET / ADDR_GENERIC / "
                   "indic_token_dict) and, critically, D124/D125 (France city and "
                   "place-name coverage) and D126/D127 (France component-order "
                   "robustness) - the exact work AGENT_PROMPT.md names as the "
                   "most valuable unexplored territory.",
            "fix": "Cap removed; the roster is 127 tasks and plan_batches.py "
                   "sizes batches from whatever build() returns.",
            "principle": "A silent cap that preferentially discards the "
                         "highest-value work is worse than no cap.",
        },
        "BUG_6_dispatch_replanned_finished_work": {
            "status": "FIXED",
            "was": "plan_batches.py planned every task in the roster regardless "
                   "of completion, so it re-dispatched delivered work and went "
                   "stale against the corrected roster.",
            "fix": "is_done() excludes any task whose declared .md deliverable "
                   "is on disk, and main() asserts the plan does not intersect "
                   "the completed set.",
        },
        "REFUTED_2_rescoped": {
            "status": "DONE - see FR-STATE-DENOMINATOR below",
            "fix": "The already_checked block in build_roster.py no longer "
                   "tells agents that France's region handling is fine. It "
                   "states the s1-only denominator explicitly and gives the "
                   "s1/s2/s3 split. dispatch_text.py was updated to match. "
                   "Verified across all task files: 0 still carry the stale "
                   "claim, 0 missing the corrected one.",
        },
    },
    "resolved_bugs": {
        "BUG_1_filename_vs_embedded_id": "RESOLVED - no task file's name "
                                         "disagrees with its id field.",
        "BUG_2_id_collisions": "RESOLVED - D075 and D078 were each claimed by "
                               "two files; the ledger now pins them and emit() "
                               "refuses duplicates.",
        "BUG_3_root_cause": "RESOLVED - id_for() was dead code; it is now on "
                            "the emit() path.",
    },
    "quarantined_orphans": {
        "count": n_orphans,
        "location": "analysis_out/findings/deprecated_slots/",
        "meaning": "Completed, legitimate work whose (dictionary, country) slot "
                   "the DICT_SCOPE fix later declared out-of-scope, so the live "
                   "roster no longer asks for it. KEPT, NOT DELETED.",
        "do_not": "Do not count these toward roster completion. They are valid "
                  "negative results, not missing work.",
    },
    "substantive_finding_still_open": {
        "id": "FR-STATE-DENOMINATOR",
        "claim": "FR_REGIONS resolves a state for 100.00% of France rows.",
        "verdict": "REFUTED as a general claim; true only for test_source1.",
        "measured": "test_source1 is 15.31% of France rows. At most 1,204,739 of "
                    "1,694,445 France rows (71.10%) resolve a state; 489,706 "
                    "(28.90%) provably cannot.",
        "root_cause": "s1 encodes geography with region names; test_s2 and "
                      "test_s3 use DEPARTMENT names (gironde 62 in s1 vs 75,104 "
                      "in s2; nord 200 vs 75,362) that are mostly absent from "
                      "FR_REGIONS.",
        "why_it_matters": "This figure was used to REJECT a France-region-gap "
                          "hypothesis. That rejection rested on a one-source "
                          "denominator and is now re-opened across s1/s2/s3.",
        "found_by": ["D073 (b01_03)", "D077 (b01_08) independently"],
        "action_taken": "The already_checked block in build_roster.py and the "
                        "dispatch prompt were both corrected, so the "
                        "outstanding agents are told the re-scoped version. The "
                        "underlying dictionary gap is NOT fixed and remains "
                        "open work.",
    },
    "secondary_finding_already_in_roster": {
        "id": "FR-FUNCTION-WORDS",
        "finding": "ADDR_CANON_FR has no entries for de, la, du, des, le, les. "
                   "In test_s2 they are 731,158 of 4,745,780 listed France "
                   "address-token mass (15.41%), against 0.37% for US and 0.01% "
                   "for India.",
        "impact": "They enter the IDF-weighted features (features.py:120-123) "
                  "and dilute IDF weighting for every French pair.",
        "action_taken": "Recorded in the already_checked block so agents build "
                        "on it instead of re-deriving it.",
    },
    "constraints_upheld": {
        "_upstream_pristine": "git status and git diff both empty, re-verified "
                              "after this session's changes",
        "dataset_unmodified": "no raw *.tsv opened by any agent",
        "network": "none used",
    },
    "next_action": {
        "ready": "YES - the roster is internally consistent and dispatchable.",
        "batch_1": ["D082", "D086", "D090", "D094", "D124", "D125", "D126",
                    "D127", "D080", "D081"],
        "why_these_first": "All are France-facing dictionary work, and D124-D127 "
                           "are the city-coverage and component-order tasks the "
                           "old 120-cap was silently discarding.",
        "progress": f"{len(done)} of {len(tasks)} tasks delivered; "
                    f"{len(tasks) - len(done)} outstanding.",
    },
}

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=1, ensure_ascii=False)

print(f"wrote {OUT}")
print(f"roster {len(tasks)} | unique ids {len({t['id'] for t in tasks})} | {fam}")
print(f"delivered {len(done)} | outstanding {len(tasks) - len(done)} | "
      f"quarantined orphans {n_orphans}")

